CLUSTAL multiple sequence alignment by MUSCLE (3.8)


NP_004889.1         MLFTVSCSKMSSIVDRDDSSIFDGLVEEDDKDKAKRVSRNKSEKKRRDQFNVLIKELGSM
XP_042937132.1      ------------MMSGHDAEFFTEFSRKQNLDRRRESSRFAARDRRGKEADIF-TDLKVV
BAJ17131.1          ------------MMADHGGDFEADCSRKRNLDRRRETSRYAARDRRGKEADIF-TDLKEV
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        --------------MSDSGCGSPDIFCERKADNRRVACKNAARERRGKESDIF-QHLQEE
                                                                                

NP_004889.1         LP----GNARKMDKSTVLQKSIDFLRKHKEITAQSDASEIRQDWKPTFLSNEEFTQLMLE
XP_042937132.1      IPIVDEATVTHVDRIAILRVALTLCRLRKVATKFLKTNL--TEEHRCLWSETT----LLE
BAJ17131.1          VPIVEEATVTHVDRIALLRVASTMFRLRKHASKLLKTAL--CEESLGLWSEAT----LLE
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        VPVVDGETVTHVDRIAYLRLASTLCRLRNKISTFLYANVEGQRDNVDAWSEDT----ISE
                                                                                

NP_004889.1         ALDGFFLAIMTDGSIIYVSESVTSLLEHLPSDLVDQSIFNFIPEGEHSEVYKILSTHLLE
XP_042937132.1      CLDGFLAIVDLDGIILYVSESVSIYLGLTQTDLTGRSLKEFIHTNDYEE-------YISC
BAJ17131.1          SLDGFMAIIDSDGVILYITESVSIYLGLTQTDLTGRSLKEFVHPNDYEE--------VSK
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        TLDGFVLIADSDGTVLYVTESVALFVGLTQTDLVGHFLSEFVHRQDYED--------LLC
                                                                                

NP_004889.1         SDSLTPEYLKSKNQLEFCCHMLRGTIDPKEPSTYEYVKFIGNFKSLNSVSSSAHNGFEGT
XP_042937132.1      DIGGAIDRGN-----GQVRTLRMKSVISPRGRNLNLKNALFKPVVCYIRSLCADNGRVRV
BAJ17131.1          SSAETSDD-------GYMTVMRMKSVISPRGRNLNLKSALFKPVNCRIRAVTDEGGRLRV
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        AMASKNGDVKPKDQMEIGTVLRMKTVITQRGRTLNLKSAVYKPINMRHTTIDTNCGRLWL
                                                                                

NP_004889.1         IQRTHRPSYEDRVCFVATVRLATPQFIKEMCTVEEPNEEFTSRHSLEWKFLFLDHRAPPI
XP_042937132.1      IQASAQPAGQGSSVFTT------------SRTTDVQSGTYMTRHTYDMKFSYVSESFNYI
BAJ17131.1          LQCSAQPAGQGSSAAMA------------AKSAEIPNGTYMTRHTCDMKFSYVSESFNYI
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        LHGSAAPAGCGYMTSAP------------MRGSETINRMFTTRHTPDMRFSYVSDGWNIP
                                                                                

NP_004889.1         IGYLPFEVLGTSGYDYYHVDDLENLAKCHEHLMQYGKGKSCYYRFLTKGQQWIWLQTHYY
XP_042937132.1      LRHEARSLMGTSFYNLVYPADLNAVVVSIREMLTKGHTRTPYYRLIGLNKSVLWVQTEAT
BAJ17131.1          LRHEARSLMGTSFYSLVHPADINAVAASMREMLSKGHTRTPYYRLIGAGRTVVWVQTEAT
JZ762439.1          ------KLIGTSFYDLVYPSDLQSVVTCMKELQSKGHCRTPFYRWLGANASVTWVQTEAT
KAH7713659.1        CRDGHRKLIGTSFYDLVYPSDLPPVVTCMKELQSKGHCRTPFYRWLGANGAVTWVQTEAT
                          .::*** *.  :  *:  :. .   :   *: .: :** :  .    *:**   

NP_004889.1         ITYHQWN-SRPEFIVCTHTVVSYAEVRAERRRELGIEESLPETAADKSQDSGSDNRINTV
XP_042937132.1      IVNHTAKGQKGQYIICVHQL-------------IGTQSER-DSFINGKKSYSTL-----M
BAJ17131.1          TVNHTSKGHKGQYVICVHEL-------------LGTQNEL-ESFMVGRD--SCLTSGSSV
JZ762439.1          TINHRSKGTKGYYVLCTHYV-------------LG-------------------------
KAH7713659.1        TINHRSKGTKGYYVLCTHYV-------------LGSQNEM-ESWNTPCSAFSCAARPVMT
                       *  :  .  :::*.* :             :*                         

NP_004889.1         SLKEALERFDHSPTPSASSRSSRKSSHTAVSD---PSSTPTKIPTDTSTPPRQHLPAHEK
XP_042937132.1      PIKQEMT----------ESSEPMRSSYNEVLQWLFRAQQRSKSPPGTLLFRTESNKNRSE
BAJ17131.1          QVKKELD----------DSPDSRKSSYDEVLQWLFRDHPNSPAPNAALFRPQDCHPKRNR
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        RVKAEID---------------------DVSDYCFGLQQPG-VECVAVEPLAEFFPRCFD
                                                                                

NP_004889.1         MVQRRSSFSSQSINSQS-VGSSLTQPVMSQATNLPIPQGMSQFQFSAQLGAMQHLKDQLE
XP_042937132.1      YNGQSTRYTAARVETIN-YNTKNGITVSGTVDFCHRNTPSISLVHNDDEGGEFHRFATEV
BAJ17131.1          LTGANSDDPDPPLATAALFASRLDSPVSSVDDITYDNSPTS--PYTNNAGLEYSPLAAGV
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        EQRPAHRHADSELDGDS--------------------------EFDAVLQWLFREDDAAP
                                                                                

NP_004889.1         QRTRMIEANIHRQQEELRKIQEQLQMVHGQGLQMFLQQSNPGLNFGSVQLSS-GNSSNIQ
XP_042937132.1      DRCRLRTNNIQTNCVE------------------------EASNRNTRDSTTLCCQSDFS
BAJ17131.1          AECELRSSSDSHSSAGGRAGGIGITNCGGSGRGGRVLASRGADSNECIPRTSRLHEFTTD
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        PQC---TSNDSLQVPAGR------------------------------------------
                                                                                

NP_004889.1         QLAPINMQGQVVPTNQIQSGMNTGHIGTTQHMIQQQTLQSTSTQSQQNVLSGHSQQTSLP
XP_042937132.1      ESSTANINAARLPTVS----------GTDIYLLPQNNITNGSTTLTGTERNPISLSTNGA
BAJ17131.1          LPSDPFLNTIRLPTIP----------STDAYALSTADAISDGASERSHLYS--SLSTPCA
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        LRAQSNPDGMKRPDGY----------GTHQ--------QPTAGQSYGSALD--VNQLPAA
                                                                                

NP_004889.1         SQTQST--LTAPLYNTMVISQPAAGSMVQIPSSMPQNSTQSAAVTTFTQDRQIRFSQGQQ
XP_042937132.1      QNTRSLTSYDPYISNNFTAATTTSSLALNNNSIHTQSNLSTTSMNCITETQRVIQNKENG
BAJ17131.1          QYSSSV-GYDPYMSASSTVAQPT--------QTHCGTAQVSTTTAMAYKDSHEEFFENPD
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        TITQPTTHYAMPVAQSIEPPQKKLDRGYGCTEMFYPENTDYSKPAS--QQGREQFGAQ--
                                                                                

NP_004889.1         LVT--------KLVTAPVACGAVMVPSTMLMGQVVTAYPTF------ATQQQQSQTLSVT
XP_042937132.1      DSDTTETIDEWQMFAPFVAHDDIMQLS----TDLQGLLPEFNFVDWIPSDPAPLPSLPAE
BAJ17131.1          LQT----------LAPFVAHEDMMQLT----TDIHSLLPDFNFADWIPADPAPLHRTNSE
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        -------------LAPYIPQEEHFTLSEPLPTDLRALFSDVDFSAYFPTD--RSENISVV
                                                                                

NP_004889.1         QQQQ-------------------------------------------------QQSSQEQ
XP_042937132.1      ERSM-------------------------------------------------KLLGNVS
BAJ17131.1          QQRSCATSGGSPALSPPASNPANTPQSSLSGCMSSPTTPGASSAPTSRHNSRATNFGTLP
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        PIQN-------------------------------------------------APYA---
                                                                                

NP_004889.1         QLTSVQQPSQAQLTQPPQQFLQTSRLLHGNPSTQLILSAAFPLQQSTFPQSHHQQHQSQQ
XP_042937132.1      IPKQITFDRSNMYANSSISLISKPNSF------------GLTAAISATPSREYEYWSNNS
BAJ17131.1          YPTPSTSPGSKSATASHYSFSNVATATDTTMSKRTVAATLVSRSQSETLSRDNNAWVHQQ
JZ762439.1          ------------------------------------------------------------
KAH7713659.1        -PKSYQMQPTKNYADDGLSFDDCS-----------------------------TFFDALG
                                                                                

NP_004889.1         QQQLS-----------------RHRTDSLPDPSKVQPQ---
XP_042937132.1      SNTMA-----------------GSRTDNNMYPT--------
BAJ17131.1          QHHPTPSVHTTVLGGGCTWTEIGTRTGGDPVLAFRRDTSAA
JZ762439.1          -----------------------------------------
KAH7713659.1        QQTMC-----------------DFVI---------------
                                                             
